name: PlushDollCustom
description: "PlushDollCustom"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  jwt_decoder: ^2.0.1
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  video_player: ^2.10.0
  intl: ^0.18.1
  cached_network_image: ^3.3.1
  lottie: ^2.2.0
  timelines_plus: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/videos/
    - assets/images/
    - assets/images/logo_hinh.png
    - assets/images/logo_chu_gif.gif
    - assets/images/apk_logo.png
    - assets/images/avatar_placeholder.png
    - assets/lottiefiles/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/apk_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/apk_logo.png"
